# Generated by Django 2.0.13 on 2019-05-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name please', max_length=180)),
                ('year', models.CharField(choices=[(None, '** Enter your Admision year here **'), ('Y1', 'Year 1'), ('Y2', 'Year 2'), ('Y3', 'Year 3'), ('Y4', 'Year 4'), ('Y5', 'Year 5')], max_length=4)),
                ('badge', models.CharField(choices=[['RK', 'Fresher'], ['HP', 'Hyper'], ['AC', 'Non-Acada'], ['LK', 'Low-Key']], help_text='Choose your student type', max_length=180)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
