# Generated by Django 2.0.13 on 2019-06-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190604_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('gender', models.CharField(choices=[['M', 'Male'], ['F', 'Female']], max_length=1)),
            ],
        ),
    ]
