# Generated by Django 2.0.13 on 2019-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='rating',
            field=models.IntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]]),
        ),
    ]
